### ISSUE TITLE
Is it possible to introduce the feedly theme?

### ISSUE THREAD

**Issue by psyciknz** [nVentiveUX/docker-ttrss#1]
Is it possible via plugins, or would I have to change the dockerfile.

**Comment by bigbrozer** [comment]
Hey !
One of the possible option to provide new themes / plugins is to bind mount the `/srv/ttrss/themes.local` folder at host level within the container (with `-v`), then install new themes into the host's folder:

```shell
docker run -d --name ttrss ... <truncated> ... -v /path/on/host/to/themes:/srv/ttrss/themes.local nventiveux/ttrss-arm32v6:latest
```

I did not tested it so please share your feedbacks ;-)

Another solution is to do your own image from the image here and add your themes (over simplified example...):

```dockerfile
FROM nventiveux/ttrss-arm32v6:latest
ADD <URL_TO_PLUGIN> /srv/ttrss/themes.local/myplugin
```

Build your image and run a container out of it.

Hope that's help !

**Comment by bigbrozer** [comment]
This is now implemented. The image is now including the feedly theme from [levito/tt-rss-feedly-theme](https://github.com/levito/tt-rss-feedly-theme).

**Comment by bigbrozer** [comment]
This is now implemented. The image is now including theme from [levito/tt-rss-feedly-theme](https://github.com/levito/tt-rss-feedly-theme).
