### ISSUE TITLE
php8-xsl

### ISSUE THREAD

**Issue by Kwbmm** [nVentiveUX/docker-ttrss#13]
Hello!
I'm testing [this](https://gitlab.com/rstromlund/xslt) plugin on my TTRss instance, which is using your image.

The plugin requires some libraries which can be installed through apk (`apk add --no-cache php8-xsl libxslt`). So far, I have manually installed them.

Would you be open to integrate those in the `Dockerfile`s? I'd be willing to make PR if you're ok with it but don't have time to do it!

**Comment by bigbrozer** [comment]
Closing as #14 has been merged. Thanks again !
