### ISSUE TITLE
Python error pyinit_main: can't initialize time on arm version 

### ISSUE THREAD

**Issue by kaiminator** [nVentiveUX/docker-ttrss#16]
Error starting arm version via docker run

```
docker run \
  --name ttrss \
  -e TZ="Europe/Berlin" \
  -e TTRSS_DB_TYPE="mysql" \
  -e TTRSS_DB_HOST="192.168.1.20" \
  -e TTRSS_DB_USER="tt-rss_user" \
  -e TTRSS_DB_PASS="$PASSWORD" \
  -e TTRSS_DB_NAME="tt-rss" \
  -e TTRSS_DB_PORT="3307" \
  -e TTRSS_SELF_URL_PATH="$URL" \
  -p 8000:80 \
  --network public_net \
  --ip 10.10.200.14 \
  -v /var/lib/docker/volumes/tt-rss:/config \
  nventiveux/ttrss-arm32v6:master

```

Error:

```
[07:37:36/8] Lock: update.lock
[07:37:36/8] Database schema is already at latest version.
Fatal Python error: pyinit_main: can't initialize time
Python runtime state: core initialized
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6fb0390 (most recent call first):
<no Python frame>

```
DB is MariaDB on an Baremetal Host. Docker runs on Raspberry Pi4

**Comment by bigbrozer** [comment]
Hi @kaiminator,
This could be related to `libseccomp2` version you are using on host (rpi4).

* Which kind of linux distribution (and version) are you running on this ?
* Could you execute `sudo apt-cache policy libseccomp2` and post results here (assuming you are using a debian-like distro) ?

Thanks !

**Comment by kaiminator** [comment]
Hi @bigbrozer 

thank you for your fast reply. Docker Host is a Rpi4 with Raspian based on buster

`Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster`

`Linux docker1 5.10.17-v7l+ #1421 SMP Thu May 27 14:00:13 BST 2021 armv7l GNU/Linux`

`root@docker1:~/create_docker_environment# apt-cache policy libseccomp2
libseccomp2:
  Installiert:           2.3.3-4
  Installationskandidat: 2.3.3-4
  Versionstabelle:
 *** 2.3.3-4 500
        500 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages
        100 /var/lib/dpkg/status`

**Comment by kaiminator** [comment]
Update:

following your hint and updating libseccomp2

`wget http://ftp.us.debian.org/debian/pool/main/libs/libseccomp/libseccomp2_2.5.1-1_armhf.deb
sudo dpkg -i libseccomp2_2.5.1-1_armhf.deb`

the container is now running.

Thank you for your support

**Comment by bigbrozer** [comment]
You're welcome !
There is [a nice explanation here](https://docs.linuxserver.io/faq#libseccomp) and a set of available options about this issue. Seems I will have to test differently and maybe refactor the image to think about arm64 :smile:
