### ISSUE TITLE
Latest tag doesn't exists on docker

### ISSUE THREAD

**Issue by mzfr** [nVentiveUX/docker-ttrss#17]
When we run the following command:

```
docker run \
  -d \
  --name ttrss \
  -e TTRSS_DB_HOST="ttrss_database" \
  -e TTRSS_DB_TYPE="pgsql" \
  -p 8000:80 \
  --network ttrss_net \
  nventiveux/ttrss-arm32v6:latest
```

It gives error saying:

```
Unable to find image 'nventiveux/ttrss:latest' locally
docker: Error response from daemon: manifest for nventiveux/ttrss:latest not found: manifest unknown: manifest unknown.
See 'docker run --help'.
```

This is because on the `dockerhub` there is no `latest` tag. 

The solutiin would be to either update the Readme or update the dockerhub to have a latest tag(recommended).

**Comment by bigbrozer** [comment]
Hi, thanks for this issue.

The `latest` tag has been removed in #8 but I understand that it could be useful especially when you have auto-updates such as [watchtower](https://containrrr.dev/watchtower/) and so on...

So I propose the following: would it be interesting to keep the `latest` tag for the always **stable** version ? (it means image will be tagged **master** / **master-YYYY.MM.DD** / **latest** when a new stable version is released keeping **develop** / **develop-YYYY.MM.DD** aside for the unstable builds).

**Comment by mzfr** [comment]
> would it be interesting to keep the latest tag for the always stable version ?
Yes that would be the best solution.
