### ISSUE TITLE
GH action 'Release' fails

### ISSUE THREAD

**Issue by Kwbmm** [nVentiveUX/docker-ttrss#27]
I've noticed that my instance was not being updated anymore, so I came here looking for hints. I saw that the GH action in charge of releasing has been failing for a month now.

I see that the problem is in this command https://github.com/nVentiveUX/docker-ttrss/blob/c04cb893d83cae0079e5c43904fd990dd6b3e344/Dockerfile#L34 , probably some APK package name has been changed. I say this, because I've tried to see if the TTRSS git repo and the feedly theme links still work, and they do. So, looking at the other commands, I believe only the APK one can fail.

**Comment by bigbrozer** [comment]
Thanks for the notice and analysis ! I'm returning from vacations so I will have a look to lock new versions of packages 🤭
