### ISSUE TITLE
How do I put this container behind a reverse proxy?

### ISSUE THREAD

**Issue by VlaK0r** [nVentiveUX/docker-ttrss#39]
Hello, friends!

I'm trying to make a reverse proxy for ttrss.
I create a config file for Apache (ttrss.conf). 

```
<VirtualHost *:80>

    ServerName ttrss.mysite.com

    ServerAdmin postmaster@mysite.com

    ErrorLog ${APACHE_LOG_DIR}/error.log

    CustomLog ${APACHE_LOG_DIR}/access.log combined

    ProxyPass / http://MyIP:8000/

    ProxyPassReverse / http://MyIP:8000/

    ProxyRequests Off

</VirtualHost>
```
When creating a container I specify  `-e TTRSS_SELF_URL_PATH=http://MyIP:8000 \`

I open the ttrss.mysite.com and everything works. But it doesn't work quite right.
Feed Debugger is not working `{"error":{"code":"E_UNAUTHORIZED","params":[]}}`

` Refusing to invoke method updatedebugger of handler feeds with invalid CSRF token. 1. backend.php(194): user_error(Refusing to invoke method updatedebugger of handler feeds with invalid CSRF token.)  Remote IP: 192.168.1.1 Request URI: /backend.php User agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0`

Does not open the original site from the pop-up menu.

```
Refusing to invoke method redirect of handler article with invalid CSRF token.
1. backend.php(194): user_error(Refusing to invoke method redirect of handler article with invalid CSRF token.)
Remote IP: 192.168.1.1
Request URI: /backend.php
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/118.0
```
Please tell me what am I doing wrong?

**Comment by bigbrozer** [comment]
Hello !

I guess the mistake is in `TTRSS_SELF_URL_PATH` which should be set to your public facing URL. I guess it should be `TTRSS_SELF_URL_PATH=https://ttrss.mysite.com`.
